from agent_team.base_expert import BaseExpert
from utils.utils import flatten_problem_description


class MetacognitiveSupervisor(BaseExpert):
    """The reflective mind: formats the final program (forward) and revises
    it when execution errors or counterfactual feedback are reported
    (backward).

    Both task templates below are the prompt templates published in
    Appendix C of the paper, kept verbatim.
    """

    ROLE_DESCRIPTION = (
        "You are the Metacognitive Supervisor in ORMind. You monitor the entire solution "
        "generation process, format the final program, and make high-level adjustments "
        "when errors are detected."
    )

    FORWARD_TASK = '''Your colleague Executive Compiler has given his answer:
{comment_text}
This answer has not been formatted. You need to format the code as the example.
The final code must has the same input args and function name as the code example:
{code_example}
You also need to return the optimized variables.
Important: Your final code should strictly use same input args, function name and return style of the code example exactly.
{attention}
Don't forget to import the library. Don't give any example usage.'''

    # Kept byte-for-byte as published in Appendix C, including the final
    # instruction's 'from PuLP import *' capitalization (the importable
    # module is lowercase ``pulp``; models normalize this in practice, and
    # changing the published prompt would alter the evaluated pipeline).
    BACKWARD_TASK = '''In your previous answer may have errors, you receive feedback about the error.
The feedback is generated by counterfactual reasoning,
which means that the feedback does not represent actual changes that need to be made to the problem conditions.
the feedback highlights where your code may have misinterpreted the original conditions.
{feedback}

For example, If you receive a message like 'Remove integer constraint on variables',
it means that your previous answer is correct only when the integer constraint is removed.
This strongly suggests that your earlier solution likely overlooked the integer constraint.
You need to add the constraint.
If you receive a message like 'Modify resource constraint to allow...',
it means that your previous answer is correct only when this constraint is modified.
This strongly suggests that your earlier solution likely has error in this constraint.
You need to doublecheck your previous code corresponding to the feedback and fix the error.

Carefully review the feedback and give the final code as the format of your previous code.
{attention}

The original problem description remains unchanged:
{problem_description}

Your previous code for analyzing the solution was:
{previous_code}

Your task is to carefully review the original problem description and the counterfactual feedback.

Remember:
Provide your corrected code in the same format as your previous code.
Do not give any example or explanation.
If the feedback is not existed in the description, you may directly use the original code.
Use "from PuLP import *" to import the library as the example.'''

    def __init__(self, model, temperature=0, base_url=None, api_key=None, fallback_model=None, usage_tracker=None):
        super().__init__(
            name="Metacognitive Supervisor",
            description="Formats the final program and revises it after feedback.",
            model=model,
            temperature=temperature,
            base_url=base_url,
            api_key=api_key,
            fallback_model=fallback_model,
            usage_tracker=usage_tracker,
        )

    def forward(self, comment_text: str, code_example: str, attention: str) -> str:
        return self.forward_chain.invoke(
            {
                "comment_text": comment_text,
                "code_example": code_example,
                "attention": attention,
            }
        ).content

    def backward(self, problem, previous_code: str, feedback: str, attention: str) -> str:
        return self.backward_chain.invoke(
            {
                "problem_description": flatten_problem_description(problem["description"]),
                "previous_code": previous_code,
                "feedback": feedback,
                "attention": attention,
            }
        ).content


Supervisor = MetacognitiveSupervisor
