"""Offline regression tests for the ORMind pipelines.

Runs without any API key: the LLM transport is replaced by a scripted
stub, so every control-flow path (Algorithm 1, syntax repair,
counterfactual revision, every Table 2 ablation flag, the standard
baseline, and extended mode) can be exercised deterministically.

Two invariants matter most:

* Data hygiene: the ground-truth objective value must never appear in any
  prompt sent to the model (scenario_no_label_leakage).
* Mechanism causality: with the same wrong program, a flagging
  counterfactual checker must change the final output and a clean checker
  must not (scenario_counterfactual_causality) — i.e. the paper's core
  mechanism is wired end to end, not a no-op.

Also covered: grading flags that deviate from the published protocol
(accept_infeasible, tolerance overrides) and their defaults, the prob_203
data erratum, empty-input boundaries, cross-problem memory isolation,
fallback-model visibility, and the paper-default runtime configuration.

Usage:
    python tests/test_offline_pipeline.py
"""

import json
import os
import shutil
import sys
from types import SimpleNamespace

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from agent_team.ormind_pipeline import ORMindPipeline, PipelineConfig, StandardPipeline
from agent_team.reflective_orchestrator import ReflectiveOrchestrator
from utils import llm as llm_module
from utils.result import Result
from utils.test_generated_code import read_test_samples, test_generated_code, write_generated_code
from utils.utils import read_OR_problem, read_problem

TEST_DIR = os.path.join("temp", "test_runs")

LPWP_ATTENTION = (
    "Note: While certain parameters in the example may not be utilized, it is imperative to include "
    "all of them in the function definition.\nThe function must return a tuple, with the first element "
    "being the objective value. A dictionary is not permitted as the return type."
)
OR_ATTENTION = (
    'The function name must be "def solve(data):" and the return must be a dict with same key as example.\n'
    "You need to give your final answer in the Todo domain of example. Don't modify other contents in the example"
)

# ----------------------------------------------------------------------
# Scripted LLM stub
# ----------------------------------------------------------------------
PROMPT_LOG = []
ROUTES = []


def fake_request(self, model, prompt):
    PROMPT_LOG.append(prompt)
    for marker, responses in ROUTES:
        if marker in prompt:
            text = responses.pop(0) if len(responses) > 1 else responses[0]
            return SimpleNamespace(
                choices=[SimpleNamespace(message=SimpleNamespace(content=text))],
                usage=SimpleNamespace(
                    prompt_tokens=max(1, len(prompt) // 4),
                    completion_tokens=max(1, len(text) // 4),
                ),
                model=model,
            )
    raise AssertionError("No scripted route matches this prompt:\n" + prompt[:500])


llm_module.OpenAICompatibleLLM._request = fake_request


def set_routes(route_map):
    PROMPT_LOG.clear()
    ROUTES.clear()
    for marker, responses in route_map.items():
        ROUTES.append((marker, list(responses) if isinstance(responses, list) else [responses]))


def fresh_dir(name):
    path = os.path.join(TEST_DIR, name)
    shutil.rmtree(path, ignore_errors=True)
    os.makedirs(path, exist_ok=True)
    return path


def grade(problem_name, samples, log_path):
    with open(log_path, "w", encoding="utf8") as handle:
        return test_generated_code(problem_name, samples, handle)


# Prompt markers (unique substrings of each template).
M_ENCODER = "extract the parameters along with their concise definitions"
M_FORMALIZE = "Give your Mathematical model of this problem."
M_COMPILER = "developing an efficient Python program"
M_SUPERVISOR_FWD = "This answer has not been formatted."
M_SUPERVISOR_BWD = "The feedback is generated by counterfactual reasoning"
M_CHECKER = "Write a Python function that identifies which specific constraints"
M_DIAGNOSIS = "The generated optimization code failed to execute."
M_CONDUCTOR = "CHOOSE THE NEXT EXPERT"
M_TERMINOLOGY = "domain knowledge terminology interpreter"
M_REVIEWER = "conduct thorough reviews of implemented code"
M_STANDARD = "You are an operations research expert."
M_EXT_ENCODER = "Return JSON only with this schema"
M_EXT_FORMALIZE = "Reasoning lens:"
M_EXT_COMPILER = "Candidate style:"
M_EXT_SELECT = "Candidate diagnostics:"
M_EXT_CHECKER = "Verification lens"
M_EXT_REVISE = "Preserve the exact function signature"

# Canned agent outputs.
ENCODER_JSON = '{"DogCapability": {"Type": "integer", "Definition": "fish carried per sled dog trip"}}'
FORMALIZE_JSON = '{"VARIABLES": "d, t integers", "CONSTRAINTS": "50d+100t<=1000, d<t", "OBJECTIVE": "max 100d+300t"}'
COMPILER_TEXT = "Here is my reference implementation:\n```python\nimport pulp\n\ndef solve_reference():\n    pass\n```"

PROB0_GOOD = (
    "def prob_0(DogCapability,TruckCapability,DogCost,TruckCost,MaxBudget):\n"
    "    return (3000.0, 0, 10)"
)
PROB0_WRONG_FEASIBLE = (
    "def prob_0(DogCapability,TruckCapability,DogCost,TruckCost,MaxBudget):\n"
    "    return (2900.0, 1, 9)"
)
PROB0_WRONG_FOR_CF = (
    "def prob_0(DogCapability,TruckCapability,DogCost,TruckCost,MaxBudget):\n"
    "    return (2000.0, 10, 5)"
)
PROB0_BROKEN = (
    "def prob_0(DogCapability,TruckCapability,DogCost,TruckCost,MaxBudget):\n"
    "    return undefined_name"
)
PROB0_NONE_OBJ = (
    "def prob_0(DogCapability,TruckCapability,DogCost,TruckCost,MaxBudget):\n"
    "    return (None, 0, 0)"
)

CHECKER_CLEAN = (
    "def counterfactual_solution_analysis(obj, var1, var2):\n"
    "    return {\n"
    '        "Modification1": {"modification_needed": False, "suggestion": None},\n'
    '        "solution_valid_without_changes": True,\n'
    "    }"
)
CHECKER_FLAG = (
    "def counterfactual_solution_analysis(obj, var1, var2):\n"
    "    return {\n"
    '        "Modification1": {"modification_needed": True,\n'
    '                          "suggestion": "Adjust constraint to ensure the number of sled dog trips is less than the number of truck trips"},\n'
    '        "solution_valid_without_changes": False,\n'
    "    }"
)

KNAPSACK_GOOD = (
    "def solve(data):\n"
    "    return {\n"
    '        "status": "Optimal",\n'
    '        "objective_value": 44.0,\n'
    '        "optimized_vars": {"x": {0: 0, 1: 1, 2: 1, 3: 0, 4: 1, 5: 1}},\n'
    "    }"
)
KNAPSACK_INFEASIBLE = (
    "def solve(data):\n"
    '    return {"status": "Infeasible"}'
)
OR_CHECKER_CLEAN = (
    "def counterfactual_solution_analysis(x, data):\n"
    "    return {\n"
    '        "Modification1": {"modification_needed": False, "suggestion": None},\n'
    '        "solution_valid_without_changes": True,\n'
    "    }"
)


def base_routes(supervisor_fwd, checker=CHECKER_CLEAN):
    return {
        M_ENCODER: ENCODER_JSON,
        M_FORMALIZE: FORMALIZE_JSON,
        M_COMPILER: COMPILER_TEXT,
        M_SUPERVISOR_FWD: supervisor_fwd,
        M_CHECKER: checker,
    }


def make_pipeline(**config_kwargs):
    return ORMindPipeline(model="stub-model", config=PipelineConfig(**config_kwargs))


def load_lpwp():
    problem = read_problem("LPWP", "prob_0")
    samples = read_test_samples("LPWP", "prob_0")
    inputs = [sample["input"] for sample in samples]
    return problem, samples, inputs


# ----------------------------------------------------------------------
# Scenarios
# ----------------------------------------------------------------------
def scenario_paper_happy_path():
    run_dir = fresh_dir("paper_happy")
    problem, samples, inputs = load_lpwp()
    set_routes(base_routes(PROB0_GOOD))

    pipeline = make_pipeline()
    code, output, stats = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert output == (3000.0, 0, 10), output
    assert stats["usage"]["llm_calls"] == 5, stats  # encoder, formalize, compile, supervise, checker
    assert stats["error_repairs"] == 0
    assert not stats["counterfactual_triggered"]

    write_generated_code(code)
    result = grade("prob_0", samples, os.path.join(run_dir, "prob_0_test_log.txt"))
    assert result == Result.ACCEPT, result

    trace_path = os.path.join(run_dir, "prob_0_ormind_trace.json")
    assert os.path.exists(trace_path)
    with open(trace_path, "r", encoding="utf8") as handle:
        trace = json.load(handle)
    assert [c["expert"] for c in trace["comments"]] == [
        "Semantic Encoder", "Formalization Thinking", "Executive Compiler",
    ]
    assert trace["counterfactual"]["status"] == "clean"
    print("PASS paper_happy_path")


def scenario_syntax_repair():
    run_dir = fresh_dir("paper_syntax_repair")
    problem, samples, inputs = load_lpwp()
    routes = base_routes(PROB0_BROKEN)
    routes[M_DIAGNOSIS] = "1. NameError: undefined_name is not defined. 2. The return statement."
    routes[M_SUPERVISOR_BWD] = PROB0_GOOD
    set_routes(routes)

    pipeline = make_pipeline()
    code, output, stats = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert stats["error_repairs"] == 1, stats
    assert output == (3000.0, 0, 10), output
    write_generated_code(code)
    assert grade("prob_0", samples, os.path.join(run_dir, "prob_0_test_log.txt")) == Result.ACCEPT
    backward_prompts = [p for p in PROMPT_LOG if M_SUPERVISOR_BWD in p]
    assert len(backward_prompts) == 1 and "Syntax error analysis" in backward_prompts[0]
    print("PASS syntax_repair")


def scenario_counterfactual_repair():
    run_dir = fresh_dir("paper_cf_repair")
    problem, samples, inputs = load_lpwp()
    routes = base_routes(PROB0_WRONG_FOR_CF, checker=CHECKER_FLAG)
    routes[M_SUPERVISOR_BWD] = PROB0_GOOD
    set_routes(routes)

    pipeline = make_pipeline()
    code, output, stats = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert stats["counterfactual_triggered"], stats
    assert output == (3000.0, 0, 10), output
    assert os.path.exists(os.path.join(run_dir, "prob_0_eval_code.py"))
    assert os.path.exists(os.path.join(run_dir, "prob_0_eval_result.txt"))
    write_generated_code(code)
    assert grade("prob_0", samples, os.path.join(run_dir, "prob_0_test_log.txt")) == Result.ACCEPT
    print("PASS counterfactual_repair")


def scenario_no_label_leakage():
    """A feasible but wrong solution must sail through untouched: the
    pipeline has no access to the reference optimum (3000), so it cannot
    know the answer is wrong, and the value 3000 must not appear in any
    prompt."""
    run_dir = fresh_dir("paper_no_leak")
    problem, samples, inputs = load_lpwp()
    set_routes(base_routes(PROB0_WRONG_FEASIBLE))

    pipeline = make_pipeline()
    code, output, stats = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert output == (2900.0, 1, 9), output
    assert stats["error_repairs"] == 0
    assert not stats["counterfactual_triggered"]
    write_generated_code(code)
    assert grade("prob_0", samples, os.path.join(run_dir, "prob_0_test_log.txt")) == Result.WRONG_ANSWER
    leaked = [p for p in PROMPT_LOG if "3000" in p]
    assert not leaked, f"ground truth leaked into {len(leaked)} prompt(s)"
    print("PASS no_label_leakage")


def scenario_complexor():
    run_dir = fresh_dir("complexor")
    problem = read_OR_problem("ComplexOR", "Knapsack")
    samples = read_test_samples("ComplexOR", "Knapsack")
    inputs = [sample["input"] for sample in samples]
    set_routes(base_routes(KNAPSACK_GOOD, checker=OR_CHECKER_CLEAN))

    pipeline = make_pipeline()
    code, output, stats = pipeline.solve("Knapsack", problem, OR_ATTENTION, inputs, run_dir)

    assert isinstance(output, dict) and output["status"] == "Optimal", output
    write_generated_code(code)
    assert grade("Knapsack", samples, os.path.join(run_dir, "Knapsack_test_log.txt")) == Result.ACCEPT
    print("PASS complexor_accept")


def scenario_grader_classification():
    run_dir = fresh_dir("grader")
    samples = read_test_samples("ComplexOR", "Knapsack")

    write_generated_code(KNAPSACK_INFEASIBLE)
    assert grade("Knapsack", samples, os.path.join(run_dir, "infeasible.txt")) == Result.MODEL_FAILURE

    write_generated_code("def solve(data):\n    raise ValueError('boom')")
    assert grade("Knapsack", samples, os.path.join(run_dir, "runtime.txt")) == Result.RUNTIME_ERROR

    write_generated_code("def some_other_function():\n    pass")
    assert grade("Knapsack", samples, os.path.join(run_dir, "missing.txt")) == Result.COMPILE_ERROR

    lpwp_samples = read_test_samples("LPWP", "prob_0")
    write_generated_code(PROB0_NONE_OBJ)
    assert grade("prob_0", lpwp_samples, os.path.join(run_dir, "none_obj.txt")) == Result.MODEL_FAILURE
    print("PASS grader_classification")


def scenario_ablation_conductor():
    run_dir = fresh_dir("ablation_conductor")
    problem, samples, inputs = load_lpwp()
    routes = base_routes(PROB0_GOOD)
    routes[M_CONDUCTOR] = ["Semantic Encoder", "Formalization Thinking", "Executive Compiler"]
    set_routes(routes)

    pipeline = make_pipeline(with_conductor=True)
    code, output, stats = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    with open(os.path.join(run_dir, "prob_0_ormind_trace.json"), "r", encoding="utf8") as handle:
        trace = json.load(handle)
    assert [c["expert"] for c in trace["comments"]] == [
        "Semantic Encoder", "Formalization Thinking", "Executive Compiler",
    ]
    assert any(M_CONDUCTOR in p for p in PROMPT_LOG)
    print("PASS ablation_conductor")


def scenario_ablation_extra_experts():
    run_dir = fresh_dir("ablation_extra_experts")
    problem, samples, inputs = load_lpwp()
    routes = base_routes(PROB0_GOOD)
    routes[M_TERMINOLOGY] = '[{"terminology": "LP", "interpretation": "linear program"}]'
    routes[M_REVIEWER] = "The implementation matches the model; no changes required."
    set_routes(routes)

    pipeline = make_pipeline(with_terminology_interpreter=True, with_code_reviewer=True)
    pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    with open(os.path.join(run_dir, "prob_0_ormind_trace.json"), "r", encoding="utf8") as handle:
        trace = json.load(handle)
    assert [c["expert"] for c in trace["comments"]] == [
        "Terminology Interpreter", "Semantic Encoder", "Formalization Thinking",
        "Executive Compiler", "Code Reviewer",
    ]
    print("PASS ablation_extra_experts")


def scenario_ablation_without_modules():
    run_dir = fresh_dir("ablation_without")
    problem, samples, inputs = load_lpwp()
    set_routes(base_routes(PROB0_GOOD))

    pipeline = make_pipeline(use_semantic_encoder=False, use_counterfactual_analysis=False)
    code, output, stats = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert not any(M_ENCODER in p for p in PROMPT_LOG), "encoder should be ablated"
    assert not any(M_CHECKER in p for p in PROMPT_LOG), "counterfactual should be ablated"
    assert output == (3000.0, 0, 10)
    print("PASS ablation_without_modules")


def scenario_standard_baseline():
    run_dir = fresh_dir("standard")
    problem, samples, inputs = load_lpwp()
    set_routes({M_STANDARD: f"```python\n{PROB0_GOOD}\n```"})

    pipeline = StandardPipeline(model="stub-model")
    code, output, stats = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert stats["usage"]["llm_calls"] == 1, stats
    assert output == (3000.0, 0, 10)
    write_generated_code(code)
    assert grade("prob_0", samples, os.path.join(run_dir, "prob_0_test_log.txt")) == Result.ACCEPT
    print("PASS standard_baseline")


def scenario_extended_mode():
    run_dir = fresh_dir("extended")
    problem, samples, inputs = load_lpwp()
    memory_file = os.path.join(TEST_DIR, "extended", "memory.jsonl")

    ext_encoder_json = json.dumps(
        {
            "problem_family": "transport_lp",
            "parameters": [],
            "entities": ["fishery"],
            "decision_signals": ["trips"],
            "objective_signals": ["maximize fish"],
            "constraint_signals": ["budget"],
            "edge_cases": [],
            "complexity_signals": [],
            "ambiguities": [],
            "decomposition_axes": [],
        }
    )
    ext_formalize_json = json.dumps(
        {
            "variables": ["d", "t"],
            "objective": "max 100d+300t",
            "constraints": ["50d+100t<=1000", "d<t"],
            "assumptions": [],
            "solver_notes": [],
            "verification_targets": [],
        }
    )
    wrong_code = (
        "def prob_0(DogCapability,TruckCapability,DogCost,TruckCost,MaxBudget):\n"
        "    return (2500.0, 2, 8)"
    )
    ext_compiler_text = f"SUMMARY:\nstub\n\nRISKS:\n- none\n\n```python\n{wrong_code}\n```"
    ext_select_json = json.dumps(
        {
            "selected_candidate": "A",
            "selection_rationale": "stub",
            "must_fix_before_run": [],
            "final_code": wrong_code,
        }
    )
    set_routes(
        {
            M_EXT_ENCODER: ext_encoder_json,
            M_EXT_FORMALIZE: ext_formalize_json,
            M_EXT_COMPILER: ext_compiler_text,
            M_EXT_SELECT: ext_select_json,
            M_EXT_CHECKER: CHECKER_CLEAN,
        }
    )

    orchestrator = ReflectiveOrchestrator(model="stub-model", memory_file=memory_file, max_candidates=2)
    code, output, stats = orchestrator.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert output == (2500.0, 2, 8), output
    write_generated_code(code)
    assert grade("prob_0", samples, os.path.join(run_dir, "prob_0_test_log.txt")) == Result.WRONG_ANSWER
    leaked = [p for p in PROMPT_LOG if "3000" in p]
    assert not leaked, "ground truth leaked into extended-mode prompts"

    with open(memory_file, "r", encoding="utf8") as handle:
        records = [json.loads(line) for line in handle if line.strip()]
    assert len(records) == 1 and records[0]["accepted"] is True
    assert "Ground Truth" not in json.dumps(records)
    preference_path = os.path.join(TEST_DIR, "extended", "memory_preference_model.json")
    assert os.path.exists(preference_path)
    with open(preference_path, "r", encoding="utf8") as handle:
        weights = json.load(handle)["weights"]
    assert weights, "preference model should have learned nonzero weights"
    print("PASS extended_mode")


def scenario_extended_consensus_counterfactual():
    """Two lens-checkers disagree: only the cross-confirmed violation may
    trigger a revision; the single-checker (hallucinated) one is logged
    as unconfirmed."""
    run_dir = fresh_dir("extended_consensus")
    problem, samples, inputs = load_lpwp()
    memory_file = os.path.join(TEST_DIR, "extended_consensus", "memory.jsonl")

    checker_a = (
        "def counterfactual_solution_analysis(obj, var1, var2):\n"
        "    return {\n"
        '        "Check1": {"modification_needed": True,\n'
        '                   "suggestion": "Adjust constraint to ensure the number of sled dog trips is less than the number of truck trips",\n'
        '                   "constraint": "var1 < var2", "violated_by": 5.0},\n'
        '        "Check2": {"modification_needed": True,\n'
        '                   "suggestion": "Spurious: cap total trips at 12",\n'
        '                   "constraint": "var1 + var2 <= 12", "violated_by": 3.0},\n'
        '        "solution_valid_without_changes": False,\n'
        "    }"
    )
    checker_b = (
        "def counterfactual_solution_analysis(obj, var1, var2):\n"
        "    return {\n"
        '        "CheckA": {"modification_needed": True,\n'
        '                   "suggestion": "Ensure sled dog trips are strictly fewer than truck trips",\n'
        '                   "constraint": "var1<var2", "violated_by": 5.0},\n'
        '        "solution_valid_without_changes": False,\n'
        "    }"
    )

    ext_encoder_json = json.dumps({"problem_family": "transport_lp", "parameters": [], "entities": [],
                                   "decision_signals": [], "objective_signals": [], "constraint_signals": [],
                                   "edge_cases": [], "complexity_signals": [], "ambiguities": [],
                                   "decomposition_axes": []})
    ext_formalize_json = json.dumps({"variables": ["d", "t"], "objective": "max", "constraints": ["c"],
                                     "assumptions": [], "solver_notes": [], "verification_targets": []})
    ext_compiler_text = f"SUMMARY:\nstub\n\nRISKS:\n- none\n\n```python\n{PROB0_WRONG_FOR_CF}\n```"
    ext_select_json = json.dumps({"selected_candidate": "A", "selection_rationale": "stub",
                                  "must_fix_before_run": [], "final_code": PROB0_WRONG_FOR_CF})
    set_routes(
        {
            M_EXT_ENCODER: ext_encoder_json,
            M_EXT_FORMALIZE: ext_formalize_json,
            M_EXT_COMPILER: ext_compiler_text,
            M_EXT_SELECT: ext_select_json,
            M_EXT_CHECKER: [checker_a, checker_b],
            M_EXT_REVISE: PROB0_GOOD,
        }
    )

    orchestrator = ReflectiveOrchestrator(model="stub-model", memory_file=memory_file, max_candidates=2)
    code, output, stats = orchestrator.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert output == (3000.0, 0, 10), output
    assert stats["counterfactual_triggered"], stats
    write_generated_code(code)
    assert grade("prob_0", samples, os.path.join(run_dir, "prob_0_test_log.txt")) == Result.ACCEPT

    with open(os.path.join(run_dir, "prob_0_ormind_trace.json"), "r", encoding="utf8") as handle:
        trace = json.load(handle)
    detail = trace["counterfactual_detail"]
    assert len(detail["confirmed"]) == 1 and len(detail["unconfirmed"]) == 1, detail
    assert "sled dog" in detail["confirmed"][0]["suggestion"]
    assert "Spurious" in detail["unconfirmed"][0]["suggestion"]

    revise_prompts = [p for p in PROMPT_LOG if M_EXT_REVISE in p]
    assert len(revise_prompts) == 1
    assert "sled dog" in revise_prompts[0]
    assert "Spurious" not in revise_prompts[0], "unconfirmed violation must not reach the reviser"
    assert os.path.exists(os.path.join(run_dir, "prob_0_eval_code_k0.py"))
    assert os.path.exists(os.path.join(run_dir, "prob_0_eval_code_k1.py"))
    print("PASS extended_consensus_counterfactual")


def scenario_counterfactual_causality():
    """Causality regression for the counterfactual loop: with the SAME wrong
    program, a flagging checker must change the final output (and its message
    must reach the revision prompt verbatim), while a clean checker must
    leave the wrong output untouched. This proves the counterfactual loop is
    causally wired, not a no-op."""
    problem, samples, inputs = load_lpwp()
    marker = "CF-MARKER-SLED-DOG-CONSTRAINT"
    checker_flag = (
        "def counterfactual_solution_analysis(obj, var1, var2):\n"
        "    return {\n"
        f'        "M1": {{"modification_needed": True, "suggestion": "{marker}"}},\n'
        '        "solution_valid_without_changes": False,\n'
        "    }"
    )

    run_dir = fresh_dir("causality_flag")
    routes = base_routes(PROB0_WRONG_FOR_CF, checker=checker_flag)
    routes[M_SUPERVISOR_BWD] = PROB0_GOOD
    set_routes(routes)
    _, output_flagged, stats_flagged = make_pipeline().solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)
    assert output_flagged == (3000.0, 0, 10), output_flagged
    assert stats_flagged["counterfactual_status"] == "discrepancy", stats_flagged
    backward = [p for p in PROMPT_LOG if M_SUPERVISOR_BWD in p]
    assert len(backward) == 1 and marker in backward[0], "checker verdict must reach the revision prompt verbatim"

    run_dir = fresh_dir("causality_clean")
    set_routes(base_routes(PROB0_WRONG_FOR_CF, checker=CHECKER_CLEAN))
    _, output_clean, stats_clean = make_pipeline().solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)
    assert output_clean == (2000.0, 10, 5), output_clean
    assert stats_clean["counterfactual_status"] == "clean", stats_clean
    assert not [p for p in PROMPT_LOG if M_SUPERVISOR_BWD in p]
    print("PASS counterfactual_causality")


def scenario_ablation_without_formalization():
    run_dir = fresh_dir("ablation_without_formalization")
    problem, samples, inputs = load_lpwp()
    set_routes(base_routes(PROB0_GOOD))

    pipeline = make_pipeline(use_formalization_thinking=False)
    code, output, stats = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert not any(M_FORMALIZE in p for p in PROMPT_LOG), "formalization should be ablated"
    assert any(M_ENCODER in p for p in PROMPT_LOG), "encoder still runs"
    assert output == (3000.0, 0, 10)
    print("PASS ablation_without_formalization")


def scenario_ablation_without_syntax_analysis():
    """--without_syntax_analysis removes ONLY the Reasoner diagnosis; the
    error-triggered revision itself remains (attribution caveat: no ablation
    row removes the bare retry)."""
    run_dir = fresh_dir("ablation_without_syntax")
    problem, samples, inputs = load_lpwp()
    routes = base_routes(PROB0_BROKEN)
    routes[M_SUPERVISOR_BWD] = PROB0_GOOD
    set_routes(routes)

    pipeline = make_pipeline(use_syntax_error_analysis=False)
    code, output, stats = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)

    assert stats["error_repairs"] == 1, stats
    assert output == (3000.0, 0, 10), output
    assert not any(M_DIAGNOSIS in p for p in PROMPT_LOG), "no Reasoner diagnosis when ablated"
    backward = [p for p in PROMPT_LOG if M_SUPERVISOR_BWD in p]
    assert len(backward) == 1 and "running-time error" in backward[0] and "Syntax error analysis" not in backward[0]
    print("PASS ablation_without_syntax_analysis")


def scenario_accept_infeasible_flag():
    """11/37 ComplexOR problems ship "Infeasible" as the reference output.
    Default (published protocol): a correct Infeasible verdict is graded
    MODEL_FAILURE. With accept_infeasible=True it is graded ACCEPT."""
    run_dir = fresh_dir("accept_infeasible")
    samples = read_test_samples("ComplexOR", "AircraftAssignment")
    assert samples[0]["output"] == ["Infeasible"]

    write_generated_code(KNAPSACK_INFEASIBLE)  # returns {"status": "Infeasible"}
    assert grade("AircraftAssignment", samples, os.path.join(run_dir, "default.txt")) == Result.MODEL_FAILURE

    with open(os.path.join(run_dir, "flag.txt"), "w", encoding="utf8") as handle:
        result = test_generated_code("AircraftAssignment", samples, handle, accept_infeasible=True)
    assert result == Result.ACCEPT, result

    # The flag must not loosen grading when the reference is numeric.
    lpwp_samples = read_test_samples("LPWP", "prob_0")
    write_generated_code(PROB0_NONE_OBJ)
    with open(os.path.join(run_dir, "numeric_ref.txt"), "w", encoding="utf8") as handle:
        result = test_generated_code("prob_0", lpwp_samples, handle, accept_infeasible=True)
    assert result == Result.MODEL_FAILURE, result
    print("PASS accept_infeasible_flag")


def scenario_prob_203_data_erratum():
    """prob_203's reference data shipped as strings ('375'), which made the
    problem unwinnable. After the erratum (numeric types, values unchanged:
    optimum 375 at (50, 0)), an exactly-correct program is ACCEPTed."""
    run_dir = fresh_dir("prob203")
    samples = read_test_samples("LPWP", "prob_203")
    assert samples[0]["output"] == [375.0]
    assert all(not isinstance(v, str) for v in samples[0]["input"].values())

    write_generated_code("def prob_203(black_milk_tea, matcha_milk_tea):\n    return (375.0, 50, 0)")
    assert grade("prob_203", samples, os.path.join(run_dir, "correct.txt")) == Result.ACCEPT

    write_generated_code("def prob_203(black_milk_tea, matcha_milk_tea):\n    return (380.0, 50, 1)")
    assert grade("prob_203", samples, os.path.join(run_dir, "wrong.txt")) == Result.WRONG_ANSWER
    print("PASS prob_203_data_erratum")


def scenario_tolerance_override():
    """Published tolerance (rel_tol=1e-3) accepts an objective that is wrong
    by up to 0.1%; --rel_tol exposes a stricter check without changing the
    default protocol."""
    run_dir = fresh_dir("tolerance")
    samples = read_test_samples("LPWP", "prob_0")  # reference optimum 3000

    write_generated_code("def prob_0(DogCapability,TruckCapability,DogCost,TruckCost,MaxBudget):\n    return (2997.5, 1, 9)")
    assert grade("prob_0", samples, os.path.join(run_dir, "default.txt")) == Result.ACCEPT  # published behaviour

    with open(os.path.join(run_dir, "strict.txt"), "w", encoding="utf8") as handle:
        result = test_generated_code("prob_0", samples, handle, rel_tol=1e-4)
    assert result == Result.WRONG_ANSWER, result
    print("PASS tolerance_override")


def scenario_grading_edge_cases():
    """Boundary configurations: an empty sample list must not grade ACCEPT,
    and an empty input list must not crash the in-pipeline runner."""
    run_dir = fresh_dir("edges")
    write_generated_code(PROB0_GOOD)
    assert grade("prob_0", [], os.path.join(run_dir, "empty.txt")) == Result.WRONG_ANSWER

    from utils.test_generated_code import run_generated_code
    assert run_generated_code("prob_0", []) is None
    print("PASS grading_edge_cases")


def scenario_consecutive_solve_isolation():
    """Two solves on the SAME pipeline instance: the memory pool and usage
    counters must reset, and no comment may leak from one problem into the
    next problem's prompts."""
    problem, samples, inputs = load_lpwp()
    pipeline = make_pipeline()

    set_routes(base_routes(PROB0_GOOD))
    ROUTES.insert(0, (M_ENCODER, ['{"RUN1_TOKEN": {"Type": "integer"}}', '{"RUN2_TOKEN": {"Type": "integer"}}']))
    run_dir = fresh_dir("isolation")
    _, _, stats1 = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)
    formalize_1 = next(p for p in PROMPT_LOG if M_FORMALIZE in p)
    assert stats1["usage"]["llm_calls"] == 5

    PROMPT_LOG.clear()
    _, _, stats2 = pipeline.solve("prob_0", problem, LPWP_ATTENTION, inputs, run_dir)
    formalize_2 = next(p for p in PROMPT_LOG if M_FORMALIZE in p)
    assert stats2["usage"]["llm_calls"] == 5, "usage must reset between problems"
    assert "RUN1_TOKEN" in formalize_1
    assert "RUN2_TOKEN" in formalize_2 and "RUN1_TOKEN" not in formalize_2, "memory pool leaked across problems"
    print("PASS consecutive_solve_isolation")


def scenario_fallback_visibility():
    """The opt-in fallback must be loud: a stderr warning plus per-model call
    counts; without a fallback configured the primary error must propagate."""
    import io
    from utils.llm import OpenAICompatibleLLM, UsageTracker

    original_request = OpenAICompatibleLLM._request

    def flaky_request(self, model, prompt):
        if model == "primary-model":
            raise RuntimeError("simulated provider error")
        return SimpleNamespace(
            choices=[SimpleNamespace(message=SimpleNamespace(content="ok"))],
            usage=SimpleNamespace(prompt_tokens=1, completion_tokens=1),
            model=model,
        )

    OpenAICompatibleLLM._request = flaky_request
    try:
        tracker = UsageTracker()
        llm = OpenAICompatibleLLM("primary-model", fallback_model="fallback-model", usage_tracker=tracker)
        captured = io.StringIO()
        original_stderr = sys.stderr
        sys.stderr = captured
        try:
            response = llm.invoke("hello")
        finally:
            sys.stderr = original_stderr
        assert response.content == "ok"
        assert tracker.snapshot()["calls_by_model"] == {"fallback-model": 1}, tracker.snapshot()
        assert "fallback" in captured.getvalue().lower(), "fallback must print a warning"

        no_fallback = OpenAICompatibleLLM("primary-model", fallback_model=None)
        try:
            no_fallback.invoke("hello")
            raise AssertionError("primary error must propagate when no fallback is configured")
        except RuntimeError:
            pass
    finally:
        OpenAICompatibleLLM._request = original_request
    print("PASS fallback_visibility")


def scenario_paper_default_config():
    """A fresh clone with no env.local and no ORMIND_* environment must
    resolve to the paper configuration: gpt-3.5-turbo on the OpenAI API,
    no fallback model."""
    from utils.config import resolve_runtime_config

    keys = ["ORMIND_MODEL", "OPENROUTER_MODEL", "OPENROUTER_BASE_URL", "OPENAI_BASE_URL",
            "OPENROUTER_API_KEY", "OPENAI_API_KEY", "ORMIND_FALLBACK_MODEL"]
    saved = {key: os.environ.pop(key) for key in keys if key in os.environ}
    env_local_backup = None
    if os.path.exists("env.local"):
        env_local_backup = "env.local.test_backup"
        os.rename("env.local", env_local_backup)
    try:
        config = resolve_runtime_config()
        assert config["model"] == "gpt-3.5-turbo", config
        assert config["base_url"] == "https://api.openai.com/v1", config
        assert config["fallback_model"] is None, "fallback must be opt-in"
    finally:
        if env_local_backup:
            os.rename(env_local_backup, "env.local")
        os.environ.update(saved)
    print("PASS paper_default_config")


def main():
    shutil.rmtree(TEST_DIR, ignore_errors=True)
    scenario_paper_happy_path()
    scenario_syntax_repair()
    scenario_counterfactual_repair()
    scenario_counterfactual_causality()
    scenario_no_label_leakage()
    scenario_complexor()
    scenario_grader_classification()
    scenario_ablation_conductor()
    scenario_ablation_extra_experts()
    scenario_ablation_without_modules()
    scenario_ablation_without_formalization()
    scenario_ablation_without_syntax_analysis()
    scenario_standard_baseline()
    scenario_accept_infeasible_flag()
    scenario_prob_203_data_erratum()
    scenario_tolerance_override()
    scenario_grading_edge_cases()
    scenario_consecutive_solve_isolation()
    scenario_fallback_visibility()
    scenario_paper_default_config()
    scenario_extended_mode()
    scenario_extended_consensus_counterfactual()
    print("\nAll offline pipeline tests passed.")


if __name__ == "__main__":
    main()
